name: project-official-deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Change to production api server
        run: sed -i 's/dev.stary-night.com/www.stary-night.com/g' `grep -lr 'dev.stary-night.com' public/official/static`
        id: deploy_to_production

      - name: Deploy to OSS
        uses: fangbinwei/aliyun-oss-website-action@v1
        with:
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
          bucket: ${{ secrets.OSS_NAME }}
          endpoint: oss-cn-hongkong.aliyuncs.com
          folder: ./public/official
